package main

import (
	"fmt"
	"net/http"
	"time"
)

func runSuite(r *Runner) {
	runID := time.Now().Format("20060102-150405")
	login := r.JSON("Auth - login", http.MethodPost, "/auth/login", map[string]any{
		"email": r.Config.Email, "password": r.Config.Password, "remember_me": true,
	}, http.StatusOK)
	r.Token = nestedString(login, "data", "token")
	ownerID := nestedString(login, "data", "id")
	if r.Token == "" || ownerID == "" {
		r.Skip("Dependent CRUD scenarios", "login failed or response did not contain token/id")
		return
	}

	r.JSON("Roles - master permissions", http.MethodGet, "/roles/master-permissions", nil, http.StatusOK)
	r.JSON("Province - get all", http.MethodGet, "/provinces?limit=100", nil, http.StatusOK)
	r.JSON("Province - get by code", http.MethodGet, "/provinces/"+r.Config.ProvinceCode, nil, http.StatusOK)
	r.JSON("Regency - target region", http.MethodGet, "/regencies?province_code="+r.Config.ProvinceCode+"&limit=500", nil, http.StatusOK)
	r.JSON("Regency - get by code", http.MethodGet, "/regencies/"+r.Config.RegencyCode, nil, http.StatusOK)
	r.JSON("District - get all", http.MethodGet, "/districts?limit=1", nil, http.StatusOK)
	r.JSON("Village - get all", http.MethodGet, "/villages?limit=1", nil, http.StatusOK)

	institution := r.Form("Institution - insert", http.MethodPost, "/institutions", form(map[string]string{
		"name": "API Test School " + runID, "email": "api-test-" + runID + "@example.test",
		"status": "active", "country": "Indonesia", "province_code": r.Config.ProvinceCode,
		"regency_code": r.Config.RegencyCode,
	}), http.StatusCreated)
	institutionID := nestedString(institution, "data", "id")
	if institutionID == "" {
		r.Skip("Learning resource regional scenario", "institution creation failed")
		return
	}
	r.JSON("Institution - get all", http.MethodGet, "/institutions?limit=5", nil, http.StatusOK)
	r.JSON("Institution - get by ID", http.MethodGet, "/institutions/"+institutionID, nil, http.StatusOK)
	r.Form("Institution - update", http.MethodPut, "/institutions/"+institutionID, form(map[string]string{"phone": "081234567890"}), http.StatusOK)

	role := r.JSON("Role - insert", http.MethodPost, "/roles", map[string]any{
		"name": "API Test Role " + runID, "description": "Generated by integration test",
		"permissions": []any{
			map[string]any{"model": "users", "action": "get-all"},
		},
	}, http.StatusCreated)
	roleID := dataString(role)
	r.JSON("Role - get all", http.MethodGet, "/roles?limit=5", nil, http.StatusOK)
	if roleID != "" {
		r.JSON("Role - get by ID", http.MethodGet, "/roles/"+roleID, nil, http.StatusOK)
		r.JSON("Role - update", http.MethodPut, "/roles/"+roleID, map[string]any{"description": "Updated by integration test"}, http.StatusOK)
	}

	var userID string
	if roleID == "" {
		r.Skip("User - insert", "role creation failed")
	} else {
		user := r.Form("User - insert", http.MethodPost, "/users", form(map[string]string{
			"name": "API Test Student", "email": "student-" + runID + "@example.test", "password": "Test12345",
			"pin": "1234", "type": "student", "role_id": roleID, "institution_id": institutionID, "is_active": "active",
		}), http.StatusCreated)
		userID = dataString(user)
	}
	r.JSON("User - get all", http.MethodGet, "/users?limit=5", nil, http.StatusOK)
	if userID != "" {
		r.JSON("User - get by ID", http.MethodGet, "/users/"+userID, nil, http.StatusOK)
		r.JSON("User - get barcode", http.MethodGet, "/users/"+userID+"/barcode", nil, http.StatusOK)
		r.Form("User - update", http.MethodPut, "/users/"+userID, form(map[string]string{"phone": "081200000001"}), http.StatusOK)
	}

	groupIDs := createRegionalLearningGroups(r, runID, institutionID)
	if len(groupIDs) > 0 && userID != "" {
		memberID := runLearningMemberScenario(r, groupIDs[0], userID)
		runLearningResourceScenario(r, runID, groupIDs, userID)
		runQuizScenario(r, runID, institutionID, groupIDs[0], userID)
		runAttendanceScenario(r, institutionID, userID, groupIDs[0])
		if memberID != "" {
			r.JSON("Learning member - archive", http.MethodDelete, "/learning-group-members/"+memberID+"/archived", nil, http.StatusOK)
			r.JSON("Learning member - delete", http.MethodDelete, "/learning-group-members/"+memberID, nil, http.StatusOK)
		}
	} else {
		r.Skip("Learning, quiz, and attendance scenarios", "learning group or user dependency was not created")
	}
	runActivityMasterScenario(r, runID, userID, ownerID)

	for index := len(groupIDs) - 1; index >= 0; index-- {
		id := groupIDs[index]
		r.JSON(fmt.Sprintf("Learning group %d - archive", index+1), http.MethodDelete, "/learning-groups/"+id+"/archived", nil, http.StatusOK)
		r.JSON(fmt.Sprintf("Learning group %d - delete", index+1), http.MethodDelete, "/learning-groups/"+id, nil, http.StatusOK)
	}
	if userID != "" {
		r.JSON("User - archive", http.MethodDelete, "/users/"+userID+"/archived", nil, http.StatusOK)
		r.JSON("User - delete", http.MethodDelete, "/users/"+userID, nil, http.StatusOK)
	}
	if roleID != "" {
		r.JSON("Role - archive", http.MethodDelete, "/roles/"+roleID+"/archived", nil, http.StatusOK)
		r.JSON("Role - delete", http.MethodDelete, "/roles/"+roleID, nil, http.StatusOK)
	}
	r.JSON("Institution - archive", http.MethodDelete, "/institutions/"+institutionID+"/archived", nil, http.StatusOK)
	r.JSON("Institution - delete", http.MethodDelete, "/institutions/"+institutionID, nil, http.StatusOK)
}

func createRegionalLearningGroups(r *Runner, runID, institutionID string) []string {
	levels := []int{1, 2}
	subjects := []string{"Matematika", "IPA"}
	ids := make([]string, 0, len(levels)*len(subjects))
	for _, level := range levels {
		for _, subject := range subjects {
			name := fmt.Sprintf("API Test Kelas %d - %s %s", level, subject, runID)
			response := r.JSON("Learning group - insert "+name, http.MethodPost, "/learning-groups", map[string]any{
				"name": name, "institution_id": institutionID, "code": fmt.Sprintf("T-%s-%d-%s", runID, level, subject),
				"type": "school-class", "level": level, "department": subject, "academic_year": "2026/2027", "is_active": true,
			}, http.StatusCreated)
			if id := dataString(response); id != "" {
				ids = append(ids, id)
			}
		}
	}
	r.JSON("Learning group - get all", http.MethodGet, "/learning-groups?limit=20", nil, http.StatusOK)
	if len(ids) > 0 {
		r.JSON("Learning group - get by ID", http.MethodGet, "/learning-groups/"+ids[0], nil, http.StatusOK)
		r.JSON("Learning group - update", http.MethodPut, "/learning-groups/"+ids[0], map[string]any{"major": "Umum"}, http.StatusOK)
	}
	return ids
}

func runLearningMemberScenario(r *Runner, groupID, userID string) string {
	created := r.JSON("Learning member - insert", http.MethodPost, "/learning-group-members", map[string]any{
		"learning_group_id": groupID, "user_id": userID, "role_in_group": "instructor",
	}, http.StatusCreated)
	id := dataString(created)
	r.JSON("Learning member - get all", http.MethodGet, "/learning-group-members?limit=10", nil, http.StatusOK)
	if id == "" {
		return ""
	}
	r.JSON("Learning member - get by ID", http.MethodGet, "/learning-group-members/"+id, nil, http.StatusOK)
	r.JSON("Learning member - update", http.MethodPut, "/learning-group-members/"+id, map[string]any{"role_in_group": "student"}, http.StatusOK)
	return id
}

func runLearningResourceScenario(r *Runner, runID string, groupIDs []string, userID string) {
	fields := form(map[string]string{
		"uploaded_user_id": userID, "title": "Modul Regional " + runID,
		"description": "Ditugaskan ke seluruh kelas dan mata pelajaran pada institution target", "type": "link",
		"file_url": "https://example.com/modules/" + runID,
	})
	fields["learning_group_ids"] = groupIDs
	created := r.Form("Learning resource - insert all target groups", http.MethodPost, "/learning-resources", fields, http.StatusCreated)
	id := dataString(created)
	r.JSON("Learning resource - get all", http.MethodGet, "/learning-resources?limit=10", nil, http.StatusOK)
	if id == "" {
		return
	}
	detail := r.JSON("Learning resource - get by ID", http.MethodGet, "/learning-resources/"+id, nil, http.StatusOK)
	assigned := nestedSliceLength(detail, "data", "learning_groups")
	r.Assert("Learning resource - assigned to every class and subject", assigned == len(groupIDs), fmt.Sprintf("expected %d assignments, received %d", len(groupIDs), assigned))
	updateFields := form(map[string]string{"title": "Modul Regional Updated " + runID})
	updateFields["learning_group_ids"] = groupIDs
	r.Form("Learning resource - update", http.MethodPut, "/learning-resources/"+id, updateFields, http.StatusOK)
	r.JSON("Learning resource - archive", http.MethodDelete, "/learning-resources/"+id+"/archived", nil, http.StatusOK)
	r.JSON("Learning resource - delete", http.MethodDelete, "/learning-resources/"+id, nil, http.StatusOK)
}

func runQuizScenario(r *Runner, runID, institutionID, groupID, userID string) {
	start := time.Now().Add(time.Hour).UTC()
	created := r.JSON("Quiz - insert", http.MethodPost, "/quizzes", map[string]any{
		"institution_id": institutionID, "learning_group_id": groupID, "created_user_id": userID,
		"title": "API Test Quiz " + runID, "description": "Integration test", "start_time": start,
		"end_time": start.Add(time.Hour), "duration_minutes": 30, "type": "quiz",
		"quiz_questions": []any{map[string]any{"question_text": "1 + 1?", "type": "multiple_choice", "points": 10,
			"correct_answer": "2", "options": []any{map[string]any{"label": "Dua", "value": "2"}, map[string]any{"label": "Tiga", "value": "3"}}}},
	}, http.StatusCreated)
	id := dataString(created)
	r.JSON("Quiz - get all", http.MethodGet, "/quizzes?limit=10", nil, http.StatusOK)
	if id == "" {
		return
	}
	r.JSON("Quiz - get by ID", http.MethodGet, "/quizzes/"+id, nil, http.StatusOK)
	r.JSON("Quiz - update", http.MethodPut, "/quizzes/"+id, map[string]any{"description": "Updated integration test"}, http.StatusOK)
	session := r.JSON("Quiz session - insert", http.MethodPost, "/quiz-sessions", map[string]any{
		"quiz_id": id, "user_id": userID, "device_info": "integration-runner", "start_time": start,
	}, http.StatusCreated)
	sessionID := dataString(session)
	r.JSON("Quiz session - get all", http.MethodGet, "/quiz-sessions?limit=10", nil, http.StatusOK)
	if sessionID != "" {
		r.JSON("Quiz session - get by ID", http.MethodGet, "/quiz-sessions/"+sessionID, nil, http.StatusOK)
		r.JSON("Quiz session - update", http.MethodPut, "/quiz-sessions/"+sessionID, map[string]any{"status": "submitted", "score": 10}, http.StatusOK)
		r.JSON("Quiz session - archive", http.MethodDelete, "/quiz-sessions/"+sessionID+"/archived", nil, http.StatusOK)
		r.JSON("Quiz session - delete", http.MethodDelete, "/quiz-sessions/"+sessionID, nil, http.StatusOK)
	}
	r.JSON("Quiz - archive", http.MethodDelete, "/quizzes/"+id+"/archived", nil, http.StatusOK)
	r.JSON("Quiz - delete", http.MethodDelete, "/quizzes/"+id, nil, http.StatusOK)
}

func runAttendanceScenario(r *Runner, institutionID, userID, groupID string) {
	reason := r.JSON("Absence reason - insert", http.MethodPost, "/attendance-absence-reasons", map[string]any{
		"institution_id": institutionID, "name": "API Test Izin", "description": "Integration test",
	}, http.StatusCreated)
	reasonID := dataString(reason)
	r.JSON("Absence reason - get all", http.MethodGet, "/attendance-absence-reasons?limit=10", nil, http.StatusOK)
	if reasonID != "" {
		r.JSON("Absence reason - get by ID", http.MethodGet, "/attendance-absence-reasons/"+reasonID, nil, http.StatusOK)
		r.JSON("Absence reason - update", http.MethodPut, "/attendance-absence-reasons/"+reasonID, map[string]any{"description": "Updated"}, http.StatusOK)
	}
	checkIn := time.Now().AddDate(0, 0, -1).UTC()
	attendance := r.JSON("Attendance - check in", http.MethodPost, "/attendance-logs/check-in", map[string]any{
		"user_id": userID, "learning_group_id": groupID, "type": "learning_group", "status": "on_time",
		"requires_check_out": true, "check_in_at": checkIn,
	}, http.StatusCreated)
	id := dataString(attendance)
	r.JSON("Attendance - get all", http.MethodGet, "/attendance-logs?limit=10", nil, http.StatusOK)
	if id != "" {
		r.JSON("Attendance - get by ID", http.MethodGet, "/attendance-logs/"+id, nil, http.StatusOK)
		r.JSON("Attendance - check out", http.MethodPut, "/attendance-logs/"+id+"/check-out", map[string]any{"check_out_at": checkIn.Add(time.Hour)}, http.StatusOK)
		r.JSON("Attendance - update", http.MethodPut, "/attendance-logs/"+id, map[string]any{"status": "late"}, http.StatusOK)
		r.JSON("Attendance - archive", http.MethodDelete, "/attendance-logs/"+id+"/archived", nil, http.StatusOK)
		r.JSON("Attendance - delete", http.MethodDelete, "/attendance-logs/"+id, nil, http.StatusOK)
	}
	if reasonID != "" {
		r.JSON("Absence reason - archive", http.MethodDelete, "/attendance-absence-reasons/"+reasonID+"/archived", nil, http.StatusOK)
		r.JSON("Absence reason - delete", http.MethodDelete, "/attendance-absence-reasons/"+reasonID, nil, http.StatusOK)
	}
}

func runActivityMasterScenario(r *Runner, runID, userID, ownerID string) {
	category := r.JSON("Activity category - insert", http.MethodPost, "/activity-categories", map[string]any{"name": "API Test Category " + runID}, http.StatusCreated)
	categoryID := dataString(category)
	r.JSON("Activity category - get all", http.MethodGet, "/activity-categories?limit=10", nil, http.StatusOK)
	if categoryID == "" {
		return
	}
	r.JSON("Activity category - get by ID", http.MethodGet, "/activity-categories/"+categoryID, nil, http.StatusOK)
	r.JSON("Activity category - update", http.MethodPut, "/activity-categories/"+categoryID, map[string]any{"description": "Updated"}, http.StatusOK)
	item := r.JSON("Activity item - insert", http.MethodPost, "/activity-items", map[string]any{
		"category_id": categoryID, "name": "API Test Activity " + runID, "type": "positive", "point_value": 1,
		"daily_limit": 1, "period_limit": 0, "period_type": "none",
	}, http.StatusCreated)
	itemID := dataString(item)
	r.JSON("Activity item - get all", http.MethodGet, "/activity-items?limit=10", nil, http.StatusOK)
	if itemID != "" {
		r.JSON("Activity item - get by ID", http.MethodGet, "/activity-items/"+itemID, nil, http.StatusOK)
		r.JSON("Activity item - update", http.MethodPut, "/activity-items/"+itemID, map[string]any{"description": "Updated"}, http.StatusOK)
		if userID != "" {
			activity := r.JSON("Activity - insert", http.MethodPost, "/activities", map[string]any{
				"activity_item_id": itemID, "user_id": userID, "recorded_user_id": ownerID,
				"description": "Integration test", "platform": "testing", "occurred_at": time.Now().AddDate(0, 0, -2).UTC(),
			}, http.StatusCreated)
			activityID := dataString(activity)
			r.JSON("Activity - get all", http.MethodGet, "/activities?limit=10", nil, http.StatusOK)
			if activityID != "" {
				r.JSON("Activity - get by ID", http.MethodGet, "/activities/"+activityID, nil, http.StatusOK)
				r.JSON("Activity - update", http.MethodPut, "/activities/"+activityID, map[string]any{"description": "Updated"}, http.StatusOK)
				r.JSON("Activity - archive", http.MethodDelete, "/activities/"+activityID+"/archived", nil, http.StatusOK)
				r.JSON("Activity - delete", http.MethodDelete, "/activities/"+activityID, nil, http.StatusOK)
			}
			bulk := r.JSON("Activity - bulk insert synchronous", http.MethodPost, "/activities/bulk", map[string]any{
				"recorded_user_id": ownerID, "platform": "testing",
				"activities": []any{map[string]any{
					"activity_item_id": itemID, "user_id": userID, "description": "Bulk integration test",
					"occurred_at": time.Now().AddDate(0, 0, -3).UTC(),
				}},
			}, http.StatusCreated)
			if bulkID := nestedFirstString(bulk, "data", "ids"); bulkID != "" {
				r.JSON("Activity bulk result - archive", http.MethodDelete, "/activities/"+bulkID+"/archived", nil, http.StatusOK)
				r.JSON("Activity bulk result - delete", http.MethodDelete, "/activities/"+bulkID, nil, http.StatusOK)
			}
		}
		r.JSON("Activity item - archive", http.MethodDelete, "/activity-items/"+itemID+"/archived", nil, http.StatusOK)
		r.JSON("Activity item - delete", http.MethodDelete, "/activity-items/"+itemID, nil, http.StatusOK)
	}
	r.JSON("Activity category - archive", http.MethodDelete, "/activity-categories/"+categoryID+"/archived", nil, http.StatusOK)
	r.JSON("Activity category - delete", http.MethodDelete, "/activity-categories/"+categoryID, nil, http.StatusOK)
}

func form(values map[string]string) map[string][]string {
	result := make(map[string][]string, len(values))
	for key, value := range values {
		result[key] = []string{value}
	}
	return result
}

func nestedSliceLength(response map[string]any, keys ...string) int {
	var current any = response
	for _, key := range keys {
		object, ok := current.(map[string]any)
		if !ok {
			return 0
		}
		current = object[key]
	}
	values, _ := current.([]any)
	return len(values)
}

func nestedFirstString(response map[string]any, keys ...string) string {
	var current any = response
	for _, key := range keys {
		object, ok := current.(map[string]any)
		if !ok {
			return ""
		}
		current = object[key]
	}
	values, ok := current.([]any)
	if !ok || len(values) == 0 {
		return ""
	}
	value, _ := values[0].(string)
	return value
}
